version: '3.1'

services:
  app:
    build: .
    ports:
      - 9000:9000
    depends_on:
      - postgresql
    env_file:
      - ./.env
    restart: always

  postgresql:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - /var/cache/postgres_data:/var/lib/postgresql/data